apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymenttemperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temp
  template:
    metadata:
      labels:
        app: temp
    spec:
      containers:
        - name: peso
          image: narirock2/temperatura_kubdev:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: temp
spec:
  selector:
    app: temp
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: NodePort
